export class AppTextStringConstants{
  static APP_NAME:string = 'SmartWork'

  static APP_DESCRIPTION:string = '移动工单协作平台'

  static PERSON_DATA_EMAIL:string = '企业邮箱/工号'

  static PERSON_DATA_PASSWORD:string = '登录密码'

  static LOGIN:string = '登录'

  static HOMEPAGE:string = '首页'

  static PREPARE_OA:string= '待办工单'

  static FINISHED_OA:string= '本月完成'

  static RECENTLY_HANDLE:string= '最近处理'








}