export class AppTextStringConstants{

  static APP_NAME:string = 'SmartWork'

  static APP_DESCRIPTION:string = '移动工单协作平台'

  static PERSON_DATA_EMAIL:string = '企业邮箱/工号'

  static PERSON_DATA_PASSWORD:string = '登录密码'

  static LOGIN:string = '登录'

  static HOMEPAGE:string = '首页'

  static WORK_ORDER_PAGE:string = '工单'

  static WORK_ORDER_DETAIL_PAGE:string = "工单详细"

  static PREPARE_OA:string= '待办工单'

  static FINISHED_OA:string= '本月完成'

  static RECENTLY_HANDLE:string= '最近处理'

  static STATUS_READY_TO_HANDLE:string= '待处理'

  static STATUS_FINISHED:string= '已完成'

  static STATUS_APPROVE:string= '审批中'

  static CREATE_NEW:string = '新建'

  static SCENE_PHOTO:string = '现场照片'

  static SUBMIT_PERSON:string = '提交人'

  static LOCATION_CHECK_IN:string = '定位打卡'

  static USER_NAME:string = '帕拉德帕'

  static REJECT_HANDLE:string = '驳回'

  static AGREE_HANDLE:string = '同意审批'




}