export class AppTextStringConstants{
  static APP_NAME:string = 'SmartWork'

  static APP_DESCRIPTION:string = '移动工单协作平台'

  static PERSON_DATA_EMAIL:string = '企业邮箱/工号'

  static PERSON_DATA_PASSWORD:string = '登录密码'

  static LOGIN:string = '登录'

  static HOMEPAGE:string = '首页'

  static WORK_ORDER_PAGE = '工单'

  static PREPARE_OA:string= '待办工单'

  static FINISHED_OA:string= '本月完成'

  static RECENTLY_HANDLE:string= '最近处理'

  static STATUS_READY_TO_HANDLE:string= '待处理'

  static STATUS_FINISHED:string= '已完成'

  static STATUS_APPROVE:string= '审批中'

  static CREATE_NEW:string = '新建'









}